export const APP_CONSTANTS = {
  KEY_RPAY_CONFIGURATION: 'getRpayConfiguration',
  KEY_CONFIGURATION: 'getRpayConfiguration',
  SET_RPAY_FLOW: 'setRpayFlow',
  KEY_TRACKING_URL: 'getTrackingUrl',
  KEY_SECTION_HEIGHT: 'getSectionHeight',

  KEY_CONTENT_ABOUT: 'contentStore/getAbout',

  KEY_MY_ITEMS: 'myItemStore/getMyItems',
  KEY_MY_UNMINTED_ITEMS: 'myItemStore/getMyUnmintedItems',
  KEY_MY_MINTED_ITEMS: 'myItemStore/getMyMintedItems',
  KEY_MY_PURCHASED_ITEMS: 'myItemStore/getMyPurchasedItems',
  KEY_MY_ITEM: 'myItemStore/myItem',
  KEY_MODAL_MESSAGE: 'getModalMessage',
  KEY_ITEM_VALIDITY: 'myItemStore/getItemValidity',

  KEY_SALES_BUTTON_LABEL: 'assetGeneralStore/getSalesButtonLabel',
  KEY_SALES_BADGE_LABEL: 'assetGeneralStore/getSalesBadgeLabel',
  KEY_RECIPIENT: 'assetGeneralStore/getRecipientAddress',

  KEY_TRANSACTION_DIALOG_MESSAGE: 'contentStore/getTransactionDialogMessage',
  KEY_WAITING_IMAGE: 'contentStore/getWaitingCSS',
  KEY_TOOL_TIP: 'contentStore/getTooltip',
  KEY_DIALOG_CONTENT: 'contentStore/getDialog',
  KEY_CONTENT_CHARITY_BY_ARTIST_ID: 'contentStore/getCharityByArtistId',
  KEY_CONTENT_ARTIST_BY_ID: 'contentStore/getArtistById',
  KEY_CONTENT_ARTIST_ID: 'contentStore/getArtistId',
  KEY_CONTENT_ARTISTS: 'contentStore/getArtists',
  KEY_CONTENT_CHARITIES: 'contentStore/getCharities',
  KEY_CONTENT_INFO_PAGE: 'contentStore/getInformationById',
  KEY_BREAK_LINE: 'contentStore/getBreakLine',
  KEY_PIXEL_BACKGROUND: 'contentStore/getPixelBackground',

  KEY_PROFILE: 'rpayAuthStore/getMyProfile',
  KEY_GAIA_STORAGE: 'rpayAuthStore/getMyProfile',

  KEY_TICKER_RATES: 'rpayStore/getTickerRates',
  KEY_DISPLAY_CARD: 'rpayStore/getDisplayCard',
  KEY_MINTING_MESSAGE: 'rpayStore/getMintingMessage',
  SET_MINTING_MESSAGE: 'rpayStore/setMintingMessage',
  KEY_PREFERRED_NETWORK: 'rpayStore/getPreferredNetwork',
  KEY_PAYMENT_OPTION_VALUE: 'rpayStore/getCurrentPaymentOption',
  SET_PAYMENT_OPTION_VALUE: 'rpayStore/setCurrentCryptoPaymentOption',
  KEY_ENABLED_NETWORKS: 'rpayStore/getEnabledNetworks',
  SET_PREFERRED_NETWORK_VALUE: 'rpayStore/setPreferredNetwork',
  KEY_PAYMENT_OPTIONS: 'rpayStore/getPaymentOptions',

  KEY_TARGET_FILE_FOR_DISPLAY: 'rpayStacksContractStore/getTargetFileForDisplay',
  KEY_GAIA_ASSET_BY_HASH: 'rpayStacksContractStore/getGaiaAssetByHash',
  KEY_GAIA_ASSETS: 'rpayStacksContractStore/getGaiaAssets',
  KEY_GAIA_ASSETS_BY_OWNER: 'rpayStacksContractStore/getGaiaAssetsByOwner',
  KEY_REGISTRY: 'rpayStacksContractStore/getRegistry',
  KEY_REGISTRY_CONTRACT_ID: 'rpayStacksContractStore/getRegistryContractId',
  KEY_TRADE_INFO_FROM_HASH: 'rpayStacksContractStore/getTradeInfoFromHash',
  KEY_APPLICATION_FROM_REGISTRY_BY_CONTRACT_ID: 'rpayStacksContractStore/getApplicationFromRegistryByContractId',
  KEY_ASSET_FROM_CONTRACT_BY_HASH: 'rpayStacksContractStore/getAssetFromContractByHash',
  KEY_ASSETS_BY_CONTRACT_ID: 'rpayStacksContractStore/getAssetsByContractId',
  KEY_ASSETS_BY_CONTRACT_ID_AND_OWNER: 'rpayStacksContractStore/getAssetsByContractIdAndOwner',
  KEY_ASSET_TRANSACTIONS: 'rpayStacksContractStore/getAssetTransactions',
  KEY_ASSET_LAST_TRANSACTION: 'rpayStacksContractStore/getAssetLastTransaction',
  KEY_ASSET_TRANSACTION: 'rpayStacksContractStore/getAssetTransaction',

  SET_CURRENT_SEARCH: 'rpaySearchStore/setCurrentSearch',
  KEY_CURRENT_SEARCH: 'rpaySearchStore/getCurrentSearch',
  KEY_ASSET: 'rpaySearchStore/getAsset',
  KEY_SEARCH_RESULTS: 'rpaySearchStore/getSearchResults'

}
